# Generated by Django 4.2 on 2024-09-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
